### ISSUE TITLE
Font doesnt seem to work properly, essentially breaking the whole extension

### ISSUE THREAD

**Issue by loawld432** [Kamiloo13/spicetify-extensions#5]
I'm not sure if I am missing a font package or something, but the original beautiful lyrics works just fine for me. However this fork does not. 
Arch Linux 
linux-cachyos-6.11.0-5
KDE Plasma Wayland 6.1.5 
NVIDIA 560.35.03 driver
RTX 3070 Max-Q

**Comment by Kamiloo13** [comment]
Beautiful lyrics and my extension uses the same font, but beautiful lyrics use separate container to display it, where I'm using the default lyrics page and just modify it. This bug is probably caused by a spicetify wrong css-map for linux builds, as every distribution of Spotify uses its own css class names.

The most important question is: Do you experience only the missing font or do you have problems with backgrounds too?
This bug is something I can't fix myself, someone has to send me their classnames that are used by their version of Spotify, so please check below for further instructions if you wish to help solve the issue.

## Testing
My friend tested this extension on:
Arch Linux x86_64
6.10.10-arch1-1
Plasma Wayland 6.1.5

And didn't encounter any issues.
![image](https://github.com/user-attachments/assets/3cf2b962-c79c-425b-af7f-81624536c08e)

## How to enable dev tools?
```
spicetify enable-devtools
```

## Next steps
After enabling developer tools, pressing right click on lyrics text and clicking "Inspect"; What is your class name on text div? It should be: `lyrics-lyricsContent-text`. 
If it's something else then please send an screenshot and if possible copy and paste the content of class `Root__main-view`. 
You can find it using ctrl + f, then select the class and do ctrl + c and paste it here either as text in "\`" as shown here: \`\`\` paste content here \`\`\` or as an attached file.

![image](https://github.com/user-attachments/assets/4bfdf610-7cd2-4dd2-829f-24c622df6fa2)
![image](https://github.com/user-attachments/assets/498c66bc-ae68-459f-9da6-af4d3f3c4769)

**Comment by loawld432** [comment]
Well, it worked when I was in fullscreen like shown, but when I had it on the side bar it wouldn't show, just a weird thin font.

**Comment by Kamiloo13** [comment]
I know this will be hard for you, but could you provide a screenshot of this? I have no support for the sidebar lyrics, those are supported only by beautiful lyrics and they show in the "now playing sidebar". I have no intention of supporting this feature as it involves calling external apis.

**Comment by loawld432** [comment]
![image](https://github.com/user-attachments/assets/e60002ae-0e5e-4fbf-a21c-49db73d77131)
This is what it looks like when I am using the original extension
![image](https://github.com/user-attachments/assets/6f5034e6-388e-432a-8280-0a20340beab7)
This is what it looks like with simple beautiful lyrics.

**Comment by loawld432** [comment]
Ignore that big ass trollface I promise I do not listen to "dark phonk"

**Comment by Kamiloo13** [comment]
The feature you are using is experimental and was introduced by spicetify. And because it's experimental; it might not be supported by extensions.
![image](https://github.com/user-attachments/assets/e92af09f-6ce7-4b94-8d38-35260772f828)

But I've decided to add some basic support for this mode. 

## Recommended steps
If you want to disable the experimental function, simply click on your profile picture > experimental features > search for "Show lyrics in the right sidebar" and disable it. If you have beautiful-lyrics activated it should pop up anyway.
![image](https://github.com/user-attachments/assets/62b056e5-f6ba-4dd0-947f-0a0b5a09e3f1)

Personally I like to have this feature off.
![image](https://github.com/user-attachments/assets/a0cd11f5-668e-4013-b958-fb5f8479c33b)

### Update should download itself after app restart. If you encounter any other issues, please reopen this issue or open a new one
